"""Run the evaluation queries and write outputs/retrieval_examples.md.
Run from the project root:
    uv run python scripts/run_retrieval_examples.py
"""

from __future__ import annotations

from datetime import datetime, timezone

import yaml

from genai_security_assistant.config import Settings
from genai_security_assistant.models.retrieval import RetrievedChunk
from genai_security_assistant.retrieval.search import SemanticRetriever


def load_queries(settings: Settings) -> list[dict]:
    path = settings.path("eval_queries")
    with path.open("r", encoding="utf-8") as handle:
        data = yaml.safe_load(handle)
    return data["queries"]


def draft_comment(
    results: list[RetrievedChunk],
    expected_docs: list[str],
) -> str:
    """Seed a relevance note from score and expected-document overlap.
    This is a starting point. After human review is required.
    """
    if not results:
        return "not relevant - no results returned"

    top = results[0]
    hit_docs = {r.metadata.document_id for r in results}
    expected = set(expected_docs)
    top_is_expected = top.metadata.document_id in expected
    any_expected = bool(hit_docs & expected)

    if top_is_expected and top.score >= 0.5:
        return (
            f"relevant - top hit is from an expected document "
            f"(score {top.score:.2f})"
        )
    if any_expected and top.score >= 0.35:
        return (
            "partially relevant - an expected document appears in top-k, "
            "but not at rank 1 or with a strong score"
        )
    return (
        f"review needed - top score {top.score:.2f}, "
        f"expected {sorted(expected)}, got {sorted(hit_docs)}"
    )

def resolve_comment(item: dict, results: list[RetrievedChunk]) -> str:
    """Prefer the handwritten comment from the query file; fall back to the
    score-based heuristic only when none is provided."""
    manual = item.get("comment")
    if manual:
        return manual.strip()
    return draft_comment(results, item.get("expected_docs", []))


def render_result(result: RetrievedChunk, preview_chars: int) -> str:
    meta = result.metadata
    return (
        f"Top-{result.rank}: {result.chunk_id} | score: {result.score:.4f}\n"
        f"  Source: {meta.source_file}\n"
        f"  Document: {meta.document_id} | Section: {meta.section or '-'}\n"
        f"  Text: {result.preview(preview_chars)}"
    )


def main() -> None:
    settings = Settings()
    preview_chars = settings.retrieval.get("preview_chars", 300)
    top_k = settings.retrieval.get("top_k", 5)

    retriever = SemanticRetriever.from_settings(settings)
    queries = load_queries(settings)

    lines: list[str] = []
    lines.append("# HW2 - Semantic Retrieval Examples\n")
    lines.append(
        f"- **Embedding model:** `{retriever.store.meta.provider}/"
        f"{retriever.store.meta.model}` "
        f"(dimension {retriever.store.meta.dimension})"
    )
    lines.append(f"- **Vector index:** FAISS `{retriever.store.meta.index_type}`, "
                 f"metric `{retriever.store.meta.metric}`")
    lines.append(f"- **Chunks indexed:** {retriever.store.meta.chunks_count}")
    lines.append(f"- **Top-k:** {top_k}")
    lines.append(f"- **Generated:** {datetime.now(timezone.utc):%Y-%m-%d %H:%M UTC}\n")
    lines.append(
        "> Generated by `scripts/run_retrieval_examples.py`. Query comments come "
        "from `configs/eval_queries.yaml`, the analysis from "
        "`configs/conclusions.md`. Re-running the script reproduces this file.\n"
    )
    lines.append("---\n")

    for item in queries:
        results = retriever.search(item["query"], top_k=top_k)
        comment = resolve_comment(item, results)

        lines.append(f"## {item['query']}\n")
        lines.append("```")
        for result in results:
            lines.append(render_result(result, preview_chars))
            lines.append("")
        lines.append("```")
        lines.append(f"**Comment:** {comment}\n")
        lines.append("---\n")

    conclusions_path = settings.path("conclusions")
    if conclusions_path.exists():
        lines.append(conclusions_path.read_text(encoding="utf-8").strip())
        lines.append("")

    output_path = settings.path("retrieval_examples")
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines), encoding="utf-8")

    print(f"Wrote {len(queries)} query results + conclusions to {output_path}")


if __name__ == "__main__":
    main()